import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowDown } from 'lucide-react';
import { FEATURED_BRAND_WORLDS } from '@/data/brandingFeatured';
import { BRAND_NAV_GROUPS } from '@/data/brands';
import './branding-hero.css';

/* Bright cinematic brand-exhibition hero for /Branding (owner brief 2026-08-26).
   Replaces a dark, left-heavy hero that talked about brand worlds without
   showing one.

   Interaction model adapted from the 21st catalogue's "Spatial Product
   Showcase": data-driven records, AnimatePresence keyed on the active id, a
   background that re-grades to the active accent, and a layoutId pill on the
   selector. That component is dark Tailwind/TypeScript; the patterns are
   re-implemented here in the AYESMAJ plain-CSS system on a bright palette.

   Every image comes from src/data/brandingFeatured.js, generated by
   scripts/branding-featured.mjs, which verifies each path exists under public/
   before writing it - the design mock listed three brands that own no assets
   at all, so the hero is built to be incapable of referencing a missing file. */

/** Verified: the "Branding & Identity" group is exactly this many brands. */
const TOTAL_BRAND_WORLDS =
  BRAND_NAV_GROUPS.find((g) => g.label === 'Branding & Identity')?.brands.length ?? 0;

/** Long enough to actually look at a brand world before it moves on. */
const AUTOPLAY_MS = 5200;

/* The five cards, in paint order. `slot` maps to the touchpoint keys the
   generator emits; a brand missing one simply renders one card fewer. */
const CARDS = [
  { slot: 'product', cls: 'bh-card--product' },
  { slot: 'campaign', cls: 'bh-card--campaign' },
  { slot: 'digital', cls: 'bh-card--digital' },
  { slot: 'identity', cls: 'bh-card--identity' },
  { slot: 'world', cls: 'bh-card--world' },
];

function BrandComposition({ brand, reduced }) {
  const cards = CARDS.filter((c) => brand.touchpoints[c.slot]);
  return (
    <div className="bh-stage">
      {/* The generations have to be absolutely stacked to cross-dissolve, but the
          plate has to sit in normal flow on mobile. Those are incompatible in one
          box, so the stack gets its own frame and the plate becomes a sibling. */}
      <div className="bh-frame">
      {/* No mode="wait" here: both generations are position:absolute inset:0, so
          they cross-dissolve in place. Serialising exit-then-enter would leave a
          half-second of empty stage on every hover. */}
      <AnimatePresence>
        <motion.div
          key={brand.id}
          className="bh-stage-inner"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: reduced ? 0.2 : 0.4, ease: [0.16, 1, 0.3, 1] }}
        >
          {cards.map((card, i) => {
            const tp = brand.touchpoints[card.slot];
            return (
              <motion.figure
                key={card.slot}
                className={`bh-card ${card.cls}`}
                initial={reduced ? { opacity: 0 } : { opacity: 0, y: 26, scale: 0.97 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                transition={
                  reduced
                    ? { duration: 0.2 }
                    : { type: 'spring', stiffness: 150, damping: 22, delay: 0.05 + i * 0.06 }
                }
              >
                {/* Eager, not lazy: these are above-the-fold hero images, and
                    under autoplay a deferred one paints as a blank card for a
                    beat. Only the active brand's five are ever in the DOM. */}
                <img
                  src={tp.src}
                  alt={`${brand.name} — ${tp.label}`}
                  loading="eager"
                  decoding="async"
                  draggable={false}
                />
                <figcaption>{tp.label}</figcaption>
              </motion.figure>
            );
          })}
        </motion.div>
      </AnimatePresence>
      </div>

      {/* The plate DOES need mode="wait": below 1023px it is position:relative and
          two stacked copies would double the section's height mid-transition.
          The exit is kept short so the serialised swap still lands under 650ms. */}
      <AnimatePresence mode="wait">
        <motion.div
          key={brand.id + '-plate'}
          className="bh-plate"
          initial={reduced ? { opacity: 0 } : { opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, transition: { duration: 0.16 } }}
          transition={{ duration: reduced ? 0.2 : 0.36, ease: [0.16, 1, 0.3, 1] }}
        >
          <span className="bh-plate-eyebrow">Selected brand world</span>
          <span className="bh-plate-name">{brand.name}</span>
          {brand.tags.length ? <span className="bh-plate-tags">{brand.tags.join(' · ')}</span> : null}
          <a className="bh-plate-link" href={brand.href}>
            View case study <ArrowRight size={13} aria-hidden="true" />
          </a>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}

export default function BrandingHero() {
  const [activeId, setActiveId] = useState(FEATURED_BRAND_WORLDS[0]?.id);
  /* Autoplay stops for good once a visitor picks a brand, and pauses while the
     pointer or keyboard focus is inside the hero or the section is scrolled out
     of view. Rotating content that ignores a deliberate choice is the reason
     carousels have the reputation they do. */
  const [autoplay, setAutoplay] = useState(true);
  const [paused, setPaused] = useState(false);
  const [inView, setInView] = useState(true);
  const reduced = useReducedMotion();
  const tabsRef = useRef(null);
  const sectionRef = useRef(null);
  const brand = FEATURED_BRAND_WORLDS.find((b) => b.id === activeId) || FEATURED_BRAND_WORLDS[0];
  const rotating = autoplay && !paused && inView && !reduced;

  const pick = useCallback((id) => { setActiveId(id); setAutoplay(false); }, []);

  /* Roving-tabindex arrow keys: the selector is a real tablist, so it must be
     operable without a pointer - the brief's "no information available only
     through hover". */
  const onKeyDown = useCallback((e) => {
    const dir = e.key === 'ArrowRight' ? 1 : e.key === 'ArrowLeft' ? -1 : 0;
    if (!dir) return;
    e.preventDefault();
    const i = FEATURED_BRAND_WORLDS.findIndex((b) => b.id === activeId);
    const next = FEATURED_BRAND_WORLDS[(i + dir + FEATURED_BRAND_WORLDS.length) % FEATURED_BRAND_WORLDS.length];
    pick(next.id);
    tabsRef.current?.querySelector(`[data-id="${next.id}"]`)?.focus();
  }, [activeId, pick]);

  /* Functional update, so the interval is created once per rotating/paused
     change rather than restarted on every tick. */
  useEffect(() => {
    if (!rotating) return undefined;
    const id = setInterval(() => {
      setActiveId((cur) => {
        const i = FEATURED_BRAND_WORLDS.findIndex((b) => b.id === cur);
        return FEATURED_BRAND_WORLDS[(i + 1) % FEATURED_BRAND_WORLDS.length].id;
      });
    }, AUTOPLAY_MS);
    return () => clearInterval(id);
  }, [rotating]);

  useEffect(() => {
    const el = sectionRef.current;
    if (!el || typeof IntersectionObserver !== 'function') return undefined;
    const io = new IntersectionObserver(([e]) => setInView(e.isIntersecting), { threshold: 0.25 });
    io.observe(el);
    return () => io.disconnect();
  }, []);

  /* Warm the brand that comes next, not the one already on screen - its <img>
     tags are fetching it anyway. Autoplay makes "next" predictable, so the swap
     lands on decoded images instead of blank cards. */
  useEffect(() => {
    const i = FEATURED_BRAND_WORLDS.findIndex((b) => b.id === activeId);
    const next = FEATURED_BRAND_WORLDS[(i + 1) % FEATURED_BRAND_WORLDS.length];
    Object.values(next?.touchpoints || {}).forEach((tp) => { new Image().src = tp.src; });
  }, [activeId]);

  if (!brand) return null;

  return (
    <section
      className="bh"
      aria-labelledby="bh-title"
      ref={sectionRef}
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocusCapture={() => setPaused(true)}
      onBlurCapture={() => setPaused(false)}
    >
      {/* Warm daylight + a wash that takes 12% of its colour from the active
          brand, so each world feels different without the page destabilising. */}
      <div className="bh-light" aria-hidden="true">
        <motion.div
          className="bh-light-accent"
          animate={{ background: `radial-gradient(58% 62% at 74% 34%, ${brand.accent}22, transparent 68%)` }}
          transition={{ duration: reduced ? 0 : 0.7, ease: [0.16, 1, 0.3, 1] }}
        />
      </div>

      <div className="bh-inner">
        <div className="bh-copy">
          <p className="bh-eyebrow">Branding · Identity · 3D · Digital</p>
          {/* Three deliberate lines. A 5/12 column cannot hold 78px display
              type on one line, so the break is authored rather than left to
              wrap "We build brand / worlds" mid-phrase. */}
          <h1 id="bh-title" className="bh-title">
            We build<br />
            brand worlds<br />
            <span className="bh-title-grad">people remember.</span>
          </h1>
          <p className="bh-lede">
            Strategy, identity, 3D, AI content and digital experiences — designed as one
            connected system from first idea to launch.
          </p>

          <div className="bh-actions">
            <a className="bh-btn bh-btn--primary" href="#brand-worlds">
              Explore brand worlds <ArrowDown size={16} aria-hidden="true" />
            </a>
            <Link className="bh-btn bh-btn--ghost" to="/Contact">
              Start a brand project <ArrowRight size={16} aria-hidden="true" />
            </Link>
          </div>
        </div>

        <div className="bh-visual">
          <BrandComposition brand={brand} reduced={reduced} />
        </div>
      </div>

      <div className="bh-selector-wrap">
        <p className="bh-selector-hint" id="bh-selector-hint">
          Choose a brand to enter its world
        </p>
        <div
          className="bh-selector"
          role="tablist"
          aria-label="Featured brand worlds"
          aria-describedby="bh-selector-hint"
          ref={tabsRef}
          onKeyDown={onKeyDown}
        >
          {FEATURED_BRAND_WORLDS.map((b) => {
            const active = b.id === activeId;
            return (
              <button
                key={b.id}
                type="button"
                role="tab"
                data-id={b.id}
                aria-selected={active}
                tabIndex={active ? 0 : -1}
                className="bh-chip"
                data-active={active}
                onClick={() => pick(b.id)}
                onMouseEnter={() => setActiveId(b.id)}
                onFocus={() => setActiveId(b.id)}
              >
                {active && (
                  <motion.span
                    layoutId="bh-chip-active"
                    className="bh-chip-surface"
                    style={{ borderColor: `${b.accent}66` }}
                    transition={{ type: 'spring', stiffness: 240, damping: 26 }}
                    aria-hidden="true"
                  >
                    {/* Makes the rotation legible: without it, a hero that
                        changes on its own reads as a glitch. Keyed on the id so
                        it replays from zero each time the active brand moves. */}
                    {rotating && (
                      <motion.span
                        key={b.id}
                        className="bh-chip-progress"
                        style={{ background: b.accent }}
                        initial={{ scaleX: 0 }}
                        animate={{ scaleX: 1 }}
                        transition={{ duration: AUTOPLAY_MS / 1000, ease: 'linear' }}
                      />
                    )}
                  </motion.span>
                )}
                <span className="bh-chip-label">{b.name}</span>
              </button>
            );
          })}
          <a className="bh-chip bh-chip--all" href="#brand-worlds">
            View all {TOTAL_BRAND_WORLDS}
          </a>
        </div>
      </div>
    </section>
  );
}
