/**
 * Resolve the homepage's real-brand showcase and write src/data/realBrands.js.
 *
 *   node scripts/real-brands.mjs
 *
 * Same contract as branding-featured.mjs: every path is verified to exist under
 * public/ before it is written, so the homepage cannot reference a missing file
 * and new brands appear by re-running this.
 *
 * The interesting part is the logo plate. These 20 logos are not a consistent
 * set - measured from their own pixels:
 *   - 8 are opaque artwork on a white background (blenday, lacroix, honey ...)
 *   - 1 is opaque on a dark background (ashe)
 *   - 6 have transparency but DARK ink (noam, kolie, syntropic, casa-ora ...)
 *   - 4 have transparency and LIGHT ink (ayesmaj, vudu, happy-jack, electric-fuel)
 * There is therefore no single chip colour that shows all of them: a white plate
 * hides the light-ink four, a dark plate hides the dark-ink six, and no plate at
 * all turns the opaque eight into white rectangles. So the plate is chosen per
 * logo from the measured luminance of its own ink, and written into the data.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { BRANDS, getBrandAssetPath } from '../src/data/brands.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PUB = path.join(ROOT, 'public');
const OUT = path.join(ROOT, 'src/data/realBrands.js');
const NL = String.fromCharCode(10);

const abs = (webPath) => path.join(PUB, decodeURIComponent(webPath).replace(/^\//, ''));
const exists = (webPath) => { try { return !!webPath && fs.existsSync(abs(webPath)); } catch { return false; } };

/* Hero card image per brand, chosen by looking at every candidate rather than
   guessing from filenames. Any brand missing from here falls back to the first
   verified section image. */
const HEROES = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/_hero-picks.json'), 'utf8'));

/* Mean luminance of the logo's own ink - alpha-weighted, so transparent padding
   does not drag the number toward whatever happens to sit in those pixels. */
const lin = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); };
async function inkProfile(file) {
  const { data } = await sharp(file).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  let sum = 0, n = 0, opaque = 0, total = 0;
  for (let i = 0; i < data.length; i += 4) {
    total++;
    if (data[i + 3] > 200) {
      opaque++;
      sum += 0.2126 * lin(data[i]) + 0.7152 * lin(data[i + 1]) + 0.0722 * lin(data[i + 2]);
      n++;
    }
  }
  return { ink: n ? sum / n : 0, coverage: opaque / total };
}

const out = [];
for (const b of BRANDS) {
  if (!b.logo) continue;                       // taxonomy buckets, not companies
  const logo = getBrandAssetPath(b, b.logo);
  if (!exists(logo)) { console.warn(`skip ${b.id}: logo missing on disk`); continue; }

  const candidates = (b.sections || [])
    .flatMap((s) => (s.images || []).map((im) => getBrandAssetPath(b, im)))
    .filter((p) => exists(p) && !/logo/i.test(p));
  const hero = (HEROES[b.id] && exists(HEROES[b.id]) ? HEROES[b.id] : candidates[0]) || null;
  if (!hero) { console.warn(`skip ${b.id}: no usable hero image`); continue; }

  const { ink, coverage } = await inkProfile(abs(logo));
  /* Opaque artwork brings its own background, so the plate just has to agree
     with it. Cut-out logos need the opposite of their ink. */
  const plate = coverage > 0.92 ? (ink > 0.4 ? 'light' : 'dark') : (ink > 0.35 ? 'dark' : 'light');

  /* The raw categories are nearly all unique ("Luxury Brand Identity",
     "CGI Commercial & Brand" ...), which makes them useless as filter chips.
     Derive a few real buckets instead; a brand can sit in more than one. */
  const hay = `${b.category || ''} ${(b.tags || []).join(' ')}`.toLowerCase();
  const tags = [];
  if (/identity|brand/.test(hay)) tags.push('Identity');
  if (/packag/.test(hay)) tags.push('Packaging');
  if (/cgi|3d|render|product/.test(hay)) tags.push('CGI & Product');
  if (/film|motion|commercial/.test(hay)) tags.push('Film & Motion');
  if (/web|digital|app|product visual/.test(hay)) tags.push('Digital');
  if (/campaign/.test(hay)) tags.push('Campaign');
  if (!tags.length) tags.push('Identity');

  out.push({
    id: b.id,
    name: b.name,
    category: b.category || 'Brand Work',
    tags,
    accent: b.accent,
    logo,
    plate,
    hero,
    href: `/BrandDetail?slug=${b.id}`,
  });
  console.log(`${b.id.padEnd(23)} plate:${plate.padEnd(6)} ink:${ink.toFixed(2)} cover:${Math.round(coverage * 100)}%`);
}

const cats = [...new Set(out.flatMap((b) => b.tags))].sort((a, b2) =>
  out.filter((x) => x.tags.includes(b2)).length - out.filter((x) => x.tags.includes(a)).length);
fs.writeFileSync(OUT,
  `/* GENERATED by scripts/real-brands.mjs - do not edit by hand.${NL}` +
  `   ${out.length} real brands, every logo and image verified on disk.${NL}` +
  `   Re-run after adding a brand: node scripts/real-brands.mjs */${NL}${NL}` +
  `export const REAL_BRANDS = ${JSON.stringify(out, null, 1)};${NL}${NL}` +
  `export const REAL_BRAND_TAGS = ${JSON.stringify(cats, null, 1)};${NL}`);

console.log(`${NL}wrote src/data/realBrands.js (${out.length} brands, ${cats.length} filter tags)`);
for (const c of cats) console.log(`  ${c.padEnd(16)} ${out.filter((x) => x.tags.includes(c)).length}`);
