import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Link } from 'react-router-dom';
import { X, ChevronLeft, ChevronRight, Play, ArrowUpRight } from 'lucide-react';
import { WORK_ARCHIVE, WORK_COUNTS } from '@/data/workArchive';
import './work-archive.css';

/* The complete archive, laid out as groups rather than one filtered pile
   (owner request 2026-09-02). Every category is on the page already; the
   buttons are jump links, not filters.

   Generated by scripts/work-archive.mjs: paths verified on disk, intrinsic
   dimensions recorded, a ~20KB poster and a 3s silent preview loop per video.
   The grid never touches an original - the 83 source videos total 5.3GB and
   one of them is 600MB, so tiles autoplay the preview and the lightbox plays
   the full asset. */

/* 3D animation leads (owner request). Anything the generator adds later that
   is not named here still renders, appended at the end. */
const CAT_ORDER = ['3D & CGI', 'AI Video', 'Branding', 'Interior', 'Characters',
  'Web', 'Logos', 'AI Posts', 'Storyboards', 'Concepts', 'Studio'];

const CATS = [
  ...CAT_ORDER.filter((c) => WORK_COUNTS[c]),
  ...Object.keys(WORK_COUNTS).filter((c) => !CAT_ORDER.includes(c)),
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const anchorId = (cat) => `wa-${slug(cat)}`;

/* Old links from the retired curated feed and the filtered archive still point
   at categories; both forms now scroll to the matching group. */
const LEGACY = {
  'Websites': 'Web', 'AI Posts': 'AI Posts', 'AI Videos': 'AI Video',
  '3D Animation': '3D & CGI', 'CGI & Motion': '3D & CGI',
  'Campaigns': 'Branding', 'Packaging & Labels': 'Branding',
};

const BY_CAT = CATS.reduce((acc, c) => {
  acc[c] = WORK_ARCHIVE.filter((i) => i.cat === c);
  return acc;
}, {});

/* The archive is lit like a corridor rather than dropped on a flat void: each
   group carries a soft wash whose hue is sampled from the brand gradient at its
   position in the page, so scrolling the archive travels gold -> copper ->
   violet -> indigo. The colour is brand-owned, not decorative: these are the
   exact stops used by the site gradient. */
const GRAD_STOPS = [[216, 183, 90], [197, 139, 87], [163, 91, 218], [122, 72, 255]];
const accentAt = (t) => {
  const x = t * (GRAD_STOPS.length - 1);
  const i = Math.min(Math.floor(x), GRAD_STOPS.length - 2);
  const f = x - i;
  return GRAD_STOPS[i].map((c, k) => Math.round(c + (GRAD_STOPS[i + 1][k] - c) * f)).join(", ");
};

const FIRST_SHOWN = 16;

function useReducedMotionLive() {
  const [reduced, setReduced] = useState(() =>
    typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    const set = () => setReduced(mq.matches);
    mq.addEventListener('change', set);
    return () => mq.removeEventListener('change', set);
  }, []);
  return reduced;
}

function useColumns() {
  const get = () => {
    if (typeof window === 'undefined') return 4;
    const w = window.innerWidth;
    return w >= 1280 ? 4 : w >= 900 ? 3 : 2;
  };
  const [cols, setCols] = useState(get);
  useEffect(() => {
    let t;
    const onResize = () => { clearTimeout(t); t = setTimeout(() => setCols(get()), 120); };
    window.addEventListener('resize', onResize);
    return () => { clearTimeout(t); window.removeEventListener('resize', onResize); };
  }, []);
  return cols;
}

const fmtDur = (s) => (s >= 60 ? `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}` : `0:${String(s).padStart(2, '0')}`);

/* A video tile only fetches and plays while it is on screen. preload="none"
   means nothing is downloaded until play() is called, so a long scroll past a
   group of films costs nothing until each one is actually visible. */
function VideoTile({ item, reduced }) {
  const ref = useRef(null);
  useEffect(() => {
    const el = ref.current;
    if (!el || reduced) return undefined;
    /* React sets `muted` as a property but not as an attribute, and iOS
       autoplay policy reads the attribute - without this, play() is refused
       on iPhone even though the element reports muted:true. */
    el.muted = true;
    el.setAttribute('muted', '');
    /* Observe the CARD, not the video. The card carries content-visibility:auto,
       so while it is offscreen its contents are not rendered and a video
       observed directly reports no box - the observer then pauses it and never
       reliably resumes. The card itself always has layout from its
       aspect-ratio, so it is the honest thing to watch. */
    const card = el.closest('.wa-card') || el;
    const io = new IntersectionObserver(([e]) => {
      if (e.isIntersecting) { const p = el.play(); if (p?.catch) p.catch(() => {}); }
      else el.pause();
    }, { rootMargin: '150px 0px' });
    io.observe(card);
    return () => { io.disconnect(); el.pause(); };
  }, [reduced]);

  return (
    <video
      ref={ref}
      src={item.preview}
      poster={item.thumb}
      muted
      loop
      playsInline
      preload="none"
      tabIndex={-1}
      aria-hidden="true"
    />
  );
}

function Lightbox({ items, index, onClose, onStep, reduced }) {
  const item = items[index];
  const boxRef = useRef(null);

  /* Focus contract from the 21st morphing-dialog source: trap Tab, focus the
     first control on open; the parent restores focus to the opening tile. */
  useEffect(() => {
    const box = boxRef.current;
    if (!box) return undefined;
    const focusables = () => box.querySelectorAll('button, [href], video, [tabindex]:not([tabindex="-1"])');
    focusables()[0]?.focus();
    const onKey = (e) => {
      if (e.key === 'Escape') { onClose(); return; }
      if (e.key === 'ArrowRight') { onStep(1); return; }
      if (e.key === 'ArrowLeft') { onStep(-1); return; }
      if (e.key === 'Tab') {
        const f = focusables();
        const first = f[0], last = f[f.length - 1];
        if (!first || !last) return;
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    };
    window.addEventListener('keydown', onKey);
    document.body.style.overflow = 'hidden';
    return () => { window.removeEventListener('keydown', onKey); document.body.style.overflow = ''; };
  }, [onClose, onStep]);

  const touch = useRef(null);
  const onTouchStart = (e) => { touch.current = { x: e.touches[0].clientX, y: e.touches[0].clientY }; };
  const onTouchEnd = (e) => {
    if (!touch.current) return;
    const dx = e.changedTouches[0].clientX - touch.current.x;
    const dy = e.changedTouches[0].clientY - touch.current.y;
    touch.current = null;
    if (Math.abs(dy) > 90 && Math.abs(dy) > Math.abs(dx)) { onClose(); return; }
    if (Math.abs(dx) > 60) onStep(dx < 0 ? 1 : -1);
  };

  if (!item) return null;
  return createPortal(
    <div className="wa-lightbox" onClick={onClose} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}>
      <div
        ref={boxRef}
        className={`wa-lightbox-box${reduced ? '' : ' wa-lightbox-box--enter'}`}
        role="dialog"
        aria-modal="true"
        aria-label={`${item.group} — ${item.cat}, item ${index + 1} of ${items.length}`}
        onClick={(e) => e.stopPropagation()}
      >
        {item.video ? (
          /* The web encode, never the master. Most masters were never deployed
             (blocked by .gitignore), nine are HEVC that no browser decodes, and
             the largest is 600MB. item.web is h264, capped at 1280 wide and
             faststart, so it plays everywhere and starts immediately. */
          <video
            key={item.web || item.src}
            src={item.web || item.src}
            poster={item.thumb}
            controls
            autoPlay={!reduced}
            muted
            loop
            playsInline
            className="wa-lightbox-media"
          />
        ) : (
          <img
            key={item.src}
            src={item.src}
            alt={`${item.group} — ${item.cat}`}
            className="wa-lightbox-media"
          />
        )}
        <div className="wa-lightbox-meta">
          <span className="wa-lightbox-tag">{item.cat}</span>
          <span className="wa-lightbox-name">{item.group}</span>
          {item.slug && (
            <Link className="wa-lightbox-link" to={`/BrandDetail?slug=${item.slug}`}>
              View case study <ArrowUpRight size={13} aria-hidden="true" />
            </Link>
          )}
          <span className="wa-lightbox-count">{index + 1} / {items.length}</span>
        </div>
        <button className="wa-lightbox-btn wa-lightbox-close" aria-label="Close" onClick={onClose}><X size={18} /></button>
        <button className="wa-lightbox-btn wa-lightbox-prev" aria-label="Previous" onClick={() => onStep(-1)}><ChevronLeft size={20} /></button>
        <button className="wa-lightbox-btn wa-lightbox-next" aria-label="Next" onClick={() => onStep(1)}><ChevronRight size={20} /></button>
      </div>
    </div>,
    document.body
  );
}

function Group({ cat, cols, reduced, onOpen, accent, side }) {
  const all = BY_CAT[cat];
  const [shown, setShown] = useState(FIRST_SHOWN);
  const list = useMemo(() => all.slice(0, shown), [all, shown]);

  /* Shortest-column distribution: known w/h means no measurement and no shift,
     each tile carries its exact aspect-ratio. */
  const columns = useMemo(() => {
    const buckets = Array.from({ length: cols }, () => ({ h: 0, items: [] }));
    for (const it of list) {
      const b = buckets.reduce((a, x) => (x.h < a.h ? x : a));
      b.items.push(it);
      b.h += it.h / it.w;
    }
    return buckets.map((b) => b.items);
  }, [list, cols]);

  return (
    <section
      className="wa-group"
      id={anchorId(cat)}
      aria-labelledby={`${anchorId(cat)}-h`}
      style={{ "--wa-accent": accent, "--wa-x": side ? "78%" : "22%" }}
    >
      <header className="wa-group-head">
        <h3 className="wa-group-title" id={`${anchorId(cat)}-h`}>{cat}</h3>
        <span className="wa-group-count">{all.length}</span>
      </header>

      <div className="wa-grid" style={{ '--wa-cols': cols }}>
        {columns.map((col, ci) => (
          <div className="wa-col" key={ci}>
            {col.map((it) => (
              <button
                key={it.thumb}
                type="button"
                className="wa-card"
                aria-label={`${it.video ? 'Play' : 'View'} ${it.group} — ${it.cat}`}
                style={{ aspectRatio: `${it.w} / ${it.h}` }}
                onClick={(e) => onOpen(cat, all.indexOf(it), e.currentTarget)}
              >
                {it.video && it.preview
                  ? <VideoTile item={it} reduced={reduced} />
                  : <img src={it.thumb} alt="" loading="lazy" decoding="async" draggable={false} />}
                {it.video && (
                  <span className="wa-card-play" aria-hidden="true">
                    <Play size={13} fill="currentColor" />
                    {it.dur ? <em>{fmtDur(it.dur)}</em> : null}
                  </span>
                )}
                <span className="wa-card-cap" aria-hidden="true">{it.group}</span>
              </button>
            ))}
          </div>
        ))}
      </div>

      {shown < all.length && (
        <div className="wa-sentinel">
          <button type="button" className="wa-more" onClick={() => setShown((v) => Math.min(v + 60, all.length))}>
            Show more {cat} <span className="wa-chip-n">{shown} / {all.length}</span>
          </button>
        </div>
      )}
    </section>
  );
}

export default function WorkArchive() {
  const cols = useColumns();
  const reduced = useReducedMotionLive();
  const [open, setOpen] = useState(null); // { cat, index }
  const openerRef = useRef(null);

  const jump = useCallback((cat) => {
    const el = document.getElementById(anchorId(cat));
    if (!el) return;
    /* Instant, not smooth. These groups are thousands of pixels apart - a
       smooth scroll from Studio back to 3D animates for several seconds, which
       is the opposite of a jump link. */
    el.scrollIntoView({ block: 'start' });
    window.history.replaceState({}, '', `#${anchorId(cat)}`);
  }, []);

  /* Land on the right group for a hash or a legacy ?a=/?f= link. */
  useEffect(() => {
    const q = new URLSearchParams(window.location.search);
    const named = q.get('a') || LEGACY[q.get('f')] || q.get('f');
    const target = CATS.includes(named) ? named : null;
    const hash = window.location.hash.replace('#', '');
    const fromHash = CATS.find((c) => anchorId(c) === hash);
    const cat = target || fromHash;
    if (!cat) return undefined;
    const t = setTimeout(() => {
      document.getElementById(anchorId(cat))?.scrollIntoView({ block: 'start' });
    }, 350);
    return () => clearTimeout(t);
  }, []);

  const items = open ? BY_CAT[open.cat] : null;
  const step = useCallback((d) => {
    setOpen((o) => (o ? { ...o, index: (o.index + d + BY_CAT[o.cat].length) % BY_CAT[o.cat].length } : o));
  }, []);
  const close = useCallback(() => { setOpen(null); openerRef.current?.focus(); }, []);
  const onOpen = useCallback((cat, index, el) => { openerRef.current = el; setOpen({ cat, index }); }, []);

  return (
    <div className="wa">
      <nav className="wa-chips" aria-label="Jump to a category">
        {CATS.map((c) => (
          <button key={c} type="button" className="wa-chip" onClick={() => jump(c)}>
            {c} <span className="wa-chip-n">{WORK_COUNTS[c]}</span>
          </button>
        ))}
      </nav>

      {CATS.map((c, i) => (
        <Group
          key={c}
          cat={c}
          cols={cols}
          reduced={reduced}
          onOpen={onOpen}
          accent={accentAt(CATS.length > 1 ? i / (CATS.length - 1) : 0)}
          side={i % 2}
        />
      ))}

      {open && (
        <Lightbox items={items} index={open.index} onClose={close} onStep={step} reduced={reduced} />
      )}
    </div>
  );
}
